version: '3.9'
services:
  client:
    image: ctf_client:latest
    ports:
      - "3000:3000"
    networks:
      nw0:
        ipv4_address: 172.20.30.10
  
  server:
    image: ctf_server:latest
    ports:
      - "5000:5000"
    networks:
      nw0:
        ipv4_address: 172.20.30.11
    
  db:
    image: ctf_db:latest
    restart: always
    networks:
      nw0:
        ipv4_address: 172.20.30.12

networks:
  nw0:
    external: true