version: '3.9'
services:
  attack_box:
    container_name: attack_box
    build:
      context: ./attack_box
      dockerfile: attack.dockerfile
    ports:
      - "22:22"
    networks:
      nw0:
        ipv4_address: 172.20.30.9

  web_tool:
    container_name: web_tool
    build: 
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - "5000:5000"
    networks:
      nw0:
        ipv4_address: 172.20.30.10
  
  db:
    container_name: db
    build: 
      context: ./psql
      dockerfile: db.dockerfile
    restart: always
    networks:
      nw0:
        ipv4_address: 172.20.30.12

networks:
  nw0:
    external: true