version: '3.9'
services:
  client:
    container_name: ctf_client
    build: 
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - "3000:3000"
    networks:
      nw0:
        ipv4_address: 172.20.30.10
  
  server:
    container_name: ctf_server
    build: 
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - "5000:5000"
    networks:
      nw0:
        ipv4_address: 172.20.30.11
    
  db:
    container_name: ctf_db
    build: 
      context: ./psql
      dockerfile: db.dockerfile
    restart: always
    networks:
      nw0:
        ipv4_address: 172.20.30.12

networks:
  nw0:
    external: true