version: '3.9'
services:
  client:
    image: ctf_client:latest
    ports:
      - "3000:3000"
    networks:
      nw0:
        ipv4_address: 172.20.30.10
  
  server:
    image: ctf_server:latest
    ports:
      - "5000:5000"
    networks:
      nw0:
        ipv4_address: 172.20.30.11
    
  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: default_database
    networks:
      nw0:
        ipv4_address: 172.20.30.12

networks:
  nw0:
    external: true