version: '3.9'
services:
  attack_box:
    container_name: attack_box
    build:
      context: ../../../
      dockerfile: challenges/andtran/attack_box/attack.dockerfile
    ports:
      - "22:22"
    networks:
      nw0:
        ipv4_address: 172.20.30.247

  web_tool:
    container_name: web_tool
    build: 
      context: ../../../
      dockerfile: challenges/andtran/server/server.dockerfile
    ports:
      - "5000:5000"
    networks:
      nw0:
        ipv4_address: 172.20.30.248
  
  db:
    container_name: db
    build: 
      context: ../../../
      dockerfile: challenges/andtran/psql/db.dockerfile
    restart: always
    networks:
      nw0:
        ipv4_address: 172.20.30.249

networks:
  nw0:
    external: true